#!/bin/bash

case "$1" in
    thaw|resume)
	# Set monitor status
	#/usr/local/bin/monitor_toggle.sh
	INTERNAL_OUTPUT="eDP1"
	if xrandr | grep -q -w "DP1 connected"; then
	    EXTERNAL_OUTPUT="DP1"
	elif xrandr | grep -q -w "HDMI1 connected"; then
	    EXTERNAL_OUTPUT="HDMI1"
	else
	    EXTERNAL_OUTPUT="NONE"
	    return 0
	fi
	if [ $EXTERNAL_OUTPUT = "DP1" ]; then
	    xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT --auto
	elif [ $EXTERNAL_OUTPUT = "HDMI1" ]; then
	    xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT --auto
	else
	    xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
	fi
;;
esac
